name: 'Calver'
description: 'generate version_number based on calver'
author: 'Ryo Okinaga'

inputs:
  schema:
    description: 'calver schema'
    required: false
    default: 'YYYY.0M.0D.MICRO'
  prefix:
    description: 'tag prefix to filter existing tags (e.g. "backend/")'
    required: false
    default: ''
outputs:
  version_number:
    description: 'generated calendar version number.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.schema }}
    - ${{ inputs.prefix }}
