name: 'Calver'
description: 'generate version_number based on calver'
author: 'Ryo Okinaga'

inputs:
  target_branch:
    description: 'target branch'
    required: false
    default: main
  schema:
    description: 'calver schema'
    required: false
    default: 'YYYY.0M.0D.MICRO'
outputs:
  version_number:
    description: 'generated calendar version number.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target_branch }}
    - ${{ inputs.schema }}
