name: 'Calver'
description: 'generate tags and releases based on calver'
author: 'Ryo Okinaga'

inputs:
  target_branch:
    description: 'target branch'
    required: false
    default: main
  schema:
    description: 'calver schema'
    required: false
    default: 'YYYY.0M.0D.MICRO'
outputs:
  tag_name:
    description: 'calver'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target_branch }}
    - ${{ inputs.version_schema }}
